### ISSUE TITLE
`env-ci`  not found

### ISSUE THREAD

**Issue by rodoabad** [pmowrer/semantic-release-github-pr#37]
Is this still being maintained?

**Comment by tehshane** [comment]
Ran into the same thing, and when I tried a workaround like
`npx -p semantic-release-github-pr -p env-ci -c "semantic-release-github-pr"`

I wound up with another error:
`An error occurred while running semantic-release: { Error: Cannot find module 'semantic-release/lib/definitions/plugins'`

Any ideas, anyone?

**Comment by saitho** [comment]
Add it as dev-dependency and then call it with npx. That solved it for me.

But now it fails with "TypeError: getGitHead is not a function". :(
