### ISSUE TITLE
semantic-release-github-pr fails on GitHub Action

### ISSUE THREAD

**Issue by Morl99** [pmowrer/semantic-release-github-pr#54]
Hello!

I tried to include this neat little module into a GitHub Action, but it fails, because the implementation does not seem to be able to fetch the currentBranch (neither for pushes nor for pull requests). I am not sure what goes wrong exactly, because there is no relevant log. All I see is that the resulting config starts like this:

`2020-10-29T22:38:02.764Z semantic-release:config options values: {
  branches: [ 'undefined' ],`

which then leads to a horrible failure.

Any idea on how to fix this? 

You can take a look at my action if you like: https://github.com/dbsystel/excote/blob/test-pr/.github/workflows/test-and-release.yaml

**Comment by XeQtr792** [comment]
@Morl99 Try using below 
for checkout
```
- name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```
for run step for releaser 
```
run: git checkout "${GITHUB_HEAD_REF}" && unset GITHUB_ACTIONS && npx semantic-release-github-pr      
```

**Comment by pmowrer** [comment]
Thanks for the report and sorry for the long delay! Instructions for GitHub Actions were added to the README (very much along the lines of what @XeQtr792 is suggesting, thank you!). Hopefully that resolves, else feel free to open up

https://github.com/pmowrer/semantic-release-github-pr/pull/59
